config/routes.rb
Rails.application.routes.draw do
resources :cats
 # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  def index
  	@cats = Cat.all
  end	

  def show
  	@cats = Cat.find(params[:id])
  end	

  def new
  	@cats = Cat.new
  end

  def create
  	@cats = Cat.new(cat_params)
	
	if @cats.save
	flash[:success] = "Data has been added!"	
	redirect_to cats_path
else 
	render 'new'
	end
end

  def edit
  	@cats = Cat.find(params[:id])
  end

  def update 
  	@cats = Cat.find(params[:id])
  
  if @cats.update(cat_params)
  	flash[:success] = "Data has been updated!"
  	redirect_to cats_path
 else
 	render 'edit'	
	end
end	

 def destroy
 	@cats = Cat.find(params[:id])
 	@cats.destroy
  flash[:alert] = "Data has been deleted!"
 	redirect_to cats_path	

end

  private 
  	def cat_params
  		params.require(:cat).permit(:name, :breed, :age)
  	end	
end

app/helpers/application_helper.rb
module ApplicationHelper

  def bootstrap_class_for flash_type
    { success: "alert-success", error: "alert-danger", alert: "alert-warning", notice: "alert-info" }.stringify_keys[flash_type.to_s] || flash_type.to_s
  end

  def flash_messages(opts = {})
    flash.each do |msg_type, message|
      concat(content_tag(:div, message, class: "alert #{bootstrap_class_for(msg_type)}", role: "alert") do 
              concat content_tag(:button, 'x', class: "close", data: { dismiss: 'alert' })
              concat message 
            end)
    	end
    	nil
	end
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/views/cats/_navigation.html.erb
<nav class="navbar navbar-default">
	<div class="container-fluid">
		<div class="nav-header">
			<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#js--navbar-collapse">
				<span class="sr-only">Toggle Navigation</span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
				<span class="icon-bar"></span>
			</button>
			<a class="navbar-brand" href="/cats">
				Cat App
			</a>
		</div>

			<div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
			<ul class="nav navbar-nav pull-right">
				<li class="active"><a href="/cats">Home</a></li>
				<li><a href="/cats/new">New</a></li>
			</ul>
		</div>	
	</div>
</nav>

app/views/cats/edit.html.erb
<%= render 'navigation' %>

<div class="container">
	<div class="row">
		
	<h3>Edit Cat Data</h3>
	<%= form_with model: @cats do |f| %>

	<div class="form-group">
		<%= f.label :Name %>
		<%= f.text_field :name, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :Breed %>
		<%= f.text_field :breed, class:'form-control' %>
	</div>

	<div class="form-group">
		<%= f.label :Age %>
		<%= f.text_field :age, class:'form-control' %>

	</div>
	
	<%= f.submit 'Update', class:'btn btn-info' %>	
	<% end %>	
	</div>
</div>

app/views/cats/index.html.erb
<%= render 'navigation' %>

<div class="container">
	<div class="row">
		<h1 class="text-center">Cat Table</h1>
		<table class="table table-bordered table-responsive table-striped text-center">
			<thead>
				<tr>
					<th>Name</th>
					<th>Breed</th>
					<th>Age</th>
					<th>Opsi</th>
				</tr>
			</thead>
			<tbody>
				<% @cats.each do |cat| %>
				<tr>
					<td><%= cat.name %></td>
					<td><%= cat.breed %></td>
					<td><%= cat.age %></td>
					<td>
						<%= link_to 'Detail', cat_path(cat), class:'btn btn-info' %>
						<%= link_to 'Edit', edit_cat_path(cat), class:'btn btn-primary' %>
						<%= link_to 'Delete', cat_path(cat), class:'btn btn-danger', method: :delete, data: {confirm: 'Do you want to delete this data?'} %>
					</td>
				</tr>
				<% end %>
			</tbody>
		</table>
	</div>
</div>

app/views/cats/new.html.erb
<%= render 'navigation' %>

<div class="container">
	<div class="row">
		<h3>Add Data</h3>
			<%= form_with model: @cats do |f|  %>
				<div class="form-group">
 					<%= f.label :Name %>
 					<%= f.text_field :name, class:'form-control', placeholder: "name", type:'text' %>
				</div>
				<div class="form-group">
	 				<%= f.label :Breed %> 	
	 				<%= f.text_field :breed, class:'form-control', placeholder: "breed", type:'text' %>
				</div>
				<div class="form-group">
			 		<%= f.label :Age %>	
			 		<%= f.text_field :age, class:'form-control', placeholder: "age", type:'number' %>
				</div>

			<%= f.submit 'Submit', class:'btn btn-primary' %>

		<% end %>
	</div>
</div>

app/views/cats/show.html.erb
<%= render 'navigation' %>

<div class="container">
	<div class="row">
		<%= form_for(@cats) do |cat| %>

			<div class="form-group">
				<%= cat.label :ID %>
				<%= cat.text_field :id, class:'form-control', type: 'text', disabled: true %>
			</div>
			<div class="form-group">
				<%= cat.label :Name %>
				<%= cat.text_field :name, class:'form-control', type: 'text', disabled: true %>
			</div>
			<div class="form-group">
				<%= cat.label :Age %>
				<%= cat.text_field :age, class:'form-control', type: 'text', disabled: true %>
			</div>
		<% end %>	
	</div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>CatApp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

    <style type="text/css">
      .alert-success {
        color:green;
      }

      .alert-warning {
        color:red;
      }
    </style>
  </head>
  <body>
    <div class="container-fluid">
    <%= flash_messages %>

    <%= yield %>
  </div>
  </body>
</html>